### ISSUE TITLE
Variable substitution section duplicated

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode-docs#1027]
There is a duplicate section "Variable substition" both in debugger and tasks doc.
This is very inconveniant since when updating that section the writer has to be aware that there are two copies. Instead of the current structure I propose to have a short page about variable that both debugger and tasks point to.

fyi @weinand @dbaeumer

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/429ec2910cda1ddb3eef1194e208cc199a6a8738
@dbaeumer @isidorn Please review https://code.visualstudio.com/docs/editor/variables-reference

**Comment by isidorn** [comment]
@gregvanl looks good. Though I still see the duplication in the debugger and taks section, optimaly they would simply point to that page. I guess you simply have not updated those docs yet.
Thanks!

**Comment by gregvanl** [comment]
@isidorn I left Validation Substitution sections in debugging.md and tasks.md for discovery and to show launch.json and tasks.json specific examples. The full list of variables should only be displaying on variables-reference.md now.

**Comment by isidorn** [comment]
@gregvanl makes sense to me. Thanks

**Comment by dbaeumer** [comment]
@gregvanl looks good to me as well.
