### ISSUE TITLE
VS Code Cannot Find Conda Environment

### ISSUE THREAD

**Issue by ccfarr** [microsoft/vscode-docs#3839]
This worked just the other day but now VS Code cannot find my conda environment named **prod**. Do not know what has changed. I have Visual Studio Code version 1.46.1. See full details below.

From terminal (the windows cmd shell from within VS Code), I can execute the following just fine:

```
conda activate prod
python my-script.py
```

When I click 'Select Python Interpreter,' my **prod** environment is not shown. After I manually select the environment, still no luck. There is a `settings.json` in my working directory, pointing to the right path as well:

```
{
    "python.pythonPath": "e:\\ProgramData\\Anaconda3\\envs\\prod\\python.exe"
}
```

BTW, the Python extension window is also complaining at lower right: "Python is not installed. Please download and install Python before using the extension. Source Python (Extension)."

Thanks in advance for any help with this.

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by ccfarr** [comment]
Please see supporting screenshot:

![vs_code](https://user-images.githubusercontent.com/16257905/86477339-38e9d480-bd16-11ea-8bdf-0754bb6dfb01.PNG)

**Comment by ccfarr** [comment]
Sorry, inadvertently closed issue.

**Comment by abhinav-TB** [comment]
Did you add your interpreter to path

**Comment by ccfarr** [comment]
Thanks for your comment. Can you be more explicit? I’m not sure what you mean. Also, note that settings.json file has the correct path to the interpreter. I also manually selected the interpreter (at the correct path) to no avail. Thanks.

**Comment by abhinav-TB** [comment]
do you have other interpreters in your system

**Comment by ccfarr** [comment]
There is the **base** interpreter but other than that only have **prod**

**Comment by abhinav-TB** [comment]
is the base interpreter showing up in the list

**Comment by ccfarr** [comment]
No

**Comment by abhinav-TB** [comment]
try running your code from conda terminal, then vs code may detect the interpreter, this also verifies that the conda env is set up properly

**Comment by ccfarr** [comment]
I was able to run my script successfully in a windows cmd shell by doing the following:
```
conda activate prod
python my-script.py
```
I even did this in the "embedded" terminal from within VS Code if that means anything. Ran fine.

**Comment by ccfarr** [comment]
Also, I may recently changed my default shell from  Windows PowerShell to the **cmd** shell. I don’t know if that was the trigger behind this issue ...

**Comment by JoshuaPartlow** [comment]
Hi @ccfarr - It sounds like you're doing the right things. Could you open an issue (or perhaps add onto microsoft/vscode-python#12463) on the Python extension repo at https://github.com/microsoft/vscode-python/issues. They should be better able to help you there. The issue I referenced is a somewhat similar sounding issue currently open about setting the interpreter that you might take a look at. A user there had a similiar conda problem and uninstalling/reinstalling the extension seemed to fix matters for them.

**Comment by ccfarr** [comment]
@JoshuaPartlow Thanks much for your response. I will try uninstall/reinstall tomorrow morning. Will let you know how it turns out. (Will also submit/add issue to Python extension repo as you suggest.) Thanks again.

**Comment by ccfarr** [comment]
@JoshuaPartlow The uninstall/reinstall of the Python extension worked! Thanks much for pointing me in this direction. I will close this issue (if okay) and notify that other issue that this solution worked for me. Thanks!

**Comment by abhinav-TB** [comment]
Happy to help

**Comment by JoshuaPartlow** [comment]
Hi @ccfarr - Glad to hear things are working for you again. Thanks for commenting on the other issue and resolving this one. If you end up with problems again, feel free to reactivate or open a new issue.

**Comment by sp-droid** [comment]
I had the same problem. My VSCode worked perfectly well until one day it didn't recognize my conda environment. Reinstalled the python extension and now works again
Thank you!

**Comment by mrhouzlane** [comment]
> settings.json

I have the same issue :

EnvironmentNameNotFound: Could not find conda environment: 

What have u done to solve it, sorry but cannot find how you managed to solve it ..

**Comment by mrhouzlane** [comment]
Fixed the issue by reinstalling python like suggested by @sp-droid .

**Comment by wyzhw** [comment]
Fixed the issue by reloading python extension in my vscode!

**Comment by plehman2000** [comment]
Did not fix mine despite reloading the python extension. Not sure what to do here

**Comment by jeremysltn** [comment]
Fixed the issue by simply switching the shell from bash to cmd.

**Comment by Dannynis** [comment]
Found another fix after any of the suggested failed,  
1) uninstall anaconda (and all its components)
2) Install fresh anaconda, in the installation first screen make sure to choose to install anaconda only for the local user in the next screen tick all the optional options (i.e make anaconda python default on the device, add to Path...)
3) proceed with the install.

**Comment by seenukarthi** [comment]
> Found another fix after any of the suggested failed,
> 
>     1. uninstall anaconda (and all its components)
> 
>     2. Install fresh anaconda, in the installation first screen make sure to choose to install anaconda only for the local user in the next screen tick all the optional options (i.e make anaconda python default on the device, add to Path...)
> 
>     3. proceed with the install.

This workked for me

**Comment by Dannynis** [comment]
> > Found another fix after any of the suggested failed,
> > ```
> > 1. uninstall anaconda (and all its components)
> > 
> > 2. Install fresh anaconda, in the installation first screen make sure to choose to install anaconda only for the local user in the next screen tick all the optional options (i.e make anaconda python default on the device, add to Path...)
> > 
> > 3. proceed with the install.
> > ```
> 
> This workked for me

glad i could help :)
