### ISSUE TITLE
Download link gives 404 error

### ISSUE THREAD

**Issue by Lagawaga** [microsoft/vscode-docs#6506]
When I try to download vs code, the download page gives a 404

**Comment by StraightUp-20** [comment]
Same here and I need it for work

**Comment by Lagawaga** [comment]
looks like it's fixed now

**Comment by victorgp** [comment]
This is still not working i am afraid... still getting 404. At least for the .deb download.

**Comment by azeek21** [comment]
@Lagawaga it's not fixed. #6508 . #6509 .
